import type { ReactNode } from 'react';

import { Icon, type IconName } from './icon.js';

/** A content card — one shape for stages, values and anything that follows. */
export function Card({
  icon,
  title,
  body,
  meta,
}: {
  icon?: IconName;
  title: string;
  body: string;
  meta?: string;
}): ReactNode {
  return (
    <article className="card">
      {icon ? (
        <span className="card__icon">
          <Icon name={icon} size={22} />
        </span>
      ) : null}
      <h3 className="card__title">{title}</h3>
      <p>{body}</p>
      {meta ? <p className="card__meta">{meta}</p> : null}
    </article>
  );
}

/** An ordered step. The numbering is generated by CSS `counter`, so the visible
 *  number can never disagree with the DOM order. */
export function Step({ title, body }: { title: string; body: string }): ReactNode {
  return (
    <li className="step">
      <h3 className="step__title">{title}</h3>
      <p>{body}</p>
    </li>
  );
}
